# docker-compose.yaml

version: "3.7"

services:
    shopping-mall-backend:
        build:
            context: .
            dockerfile: Dockerfile
        # volumes:
        #     - ./src:/shopping-mall/src
        ports:
            - 3000:3000
        env_file:
            - .env.dev

    # docker-database:
    #     image: mysql:latest
    #     ports:
    #         - 3306:3306
    #     environment:
    #         MYSQL_ROOT_PASSWORD: 1234
    #         MYSQL_DATABASE: shopping-mall
