import {MigrationInterface, QueryRunner} from "typeorm";

export class updateDB1684503950642 implements MigrationInterface {
    name = 'updateDB1684503950642'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`campground_tag\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`campground_tag\` DROP COLUMN \`campground_tag_id\``);
        await queryRunner.query(`ALTER TABLE \`campground_tag\` DROP COLUMN \`tag_name\``);
        await queryRunner.query(`ALTER TABLE \`member\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`member\` DROP COLUMN \`member_id\``);
        await queryRunner.query(`ALTER TABLE \`member\` DROP COLUMN \`phone_number\``);
        await queryRunner.query(`ALTER TABLE \`options\` DROP COLUMN \`walking_trails\``);
        await queryRunner.query(`ALTER TABLE \`options\` DROP COLUMN \`athletic_facilities\``);
        await queryRunner.query(`ALTER TABLE \`options\` DROP COLUMN \`convenience_store\``);
        await queryRunner.query(`ALTER TABLE \`options\` DROP COLUMN \`sports_field\``);
        await queryRunner.query(`ALTER TABLE \`options\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`options\` DROP COLUMN \`campground_id\``);
        await queryRunner.query(`ALTER TABLE \`dibs\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`dibs\` ADD PRIMARY KEY (\`campground_id\`)`);
        await queryRunner.query(`ALTER TABLE \`dibs\` DROP COLUMN \`member_id\``);
        await queryRunner.query(`ALTER TABLE \`dibs\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`dibs\` DROP COLUMN \`campground_id\``);
        await queryRunner.query(`ALTER TABLE \`referrals\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`referrals\` ADD PRIMARY KEY (\`campground_id\`)`);
        await queryRunner.query(`ALTER TABLE \`referrals\` DROP COLUMN \`member_id\``);
        await queryRunner.query(`ALTER TABLE \`referrals\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`referrals\` DROP COLUMN \`campground_id\``);
        await queryRunner.query(`ALTER TABLE \`reservation\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`reservation\` DROP COLUMN \`reservation_id\``);
        await queryRunner.query(`ALTER TABLE \`reservation\` DROP COLUMN \`start_date\``);
        await queryRunner.query(`ALTER TABLE \`reservation\` DROP COLUMN \`end_date\``);
        await queryRunner.query(`ALTER TABLE \`reservation\` DROP COLUMN \`users_number\``);
        await queryRunner.query(`ALTER TABLE \`reservation\` DROP COLUMN \`length_of_stay\``);
        await queryRunner.query(`ALTER TABLE \`reservation\` DROP COLUMN \`camping_type\``);
        await queryRunner.query(`ALTER TABLE \`reservation\` DROP COLUMN \`member_id\``);
        await queryRunner.query(`ALTER TABLE \`reservation\` DROP COLUMN \`campground_id\``);
        await queryRunner.query(`ALTER TABLE \`review\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`review\` ADD PRIMARY KEY (\`campground_id\`)`);
        await queryRunner.query(`ALTER TABLE \`review\` DROP COLUMN \`member_id\``);
        await queryRunner.query(`ALTER TABLE \`review\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`review\` DROP COLUMN \`campground_id\``);
        await queryRunner.query(`ALTER TABLE \`tent\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`tent\` DROP COLUMN \`tent_id\``);
        await queryRunner.query(`ALTER TABLE \`tent\` DROP COLUMN \`camping_type\``);
        await queryRunner.query(`ALTER TABLE \`tent\` DROP COLUMN \`residual_quantity\``);
        await queryRunner.query(`ALTER TABLE \`tent\` DROP COLUMN \`weekday_prices\``);
        await queryRunner.query(`ALTER TABLE \`tent\` DROP COLUMN \`weekend_prices\``);
        await queryRunner.query(`ALTER TABLE \`tent\` DROP COLUMN \`campground_id\``);
        await queryRunner.query(`ALTER TABLE \`campground_tag\` ADD \`campgroundTagId\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`campground_tag\` ADD \`tagName\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`member\` ADD \`memberId\` varchar(255) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`member\` ADD \`phoneNumber\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`options\` ADD \`walkingTrails\` tinyint NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`options\` ADD \`athleticFacilities\` tinyint NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`options\` ADD \`convenienceStore\` tinyint NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`options\` ADD \`sportsField\` tinyint NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`options\` ADD \`campgroundId\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`options\` ADD UNIQUE INDEX \`IDX_5a9ff2afab984e97e21ae16b41\` (\`campgroundId\`)`);
        await queryRunner.query(`ALTER TABLE \`dibs\` ADD \`memberId\` varchar(255) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`dibs\` ADD \`campgroundId\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`dibs\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`dibs\` ADD PRIMARY KEY (\`memberId\`, \`campgroundId\`)`);
        await queryRunner.query(`ALTER TABLE \`referrals\` ADD \`memberId\` varchar(255) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`referrals\` ADD \`campgroundId\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`referrals\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`referrals\` ADD PRIMARY KEY (\`memberId\`, \`campgroundId\`)`);
        await queryRunner.query(`ALTER TABLE \`reservation\` ADD \`reservationId\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`reservation\` ADD \`startDate\` datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`reservation\` ADD \`endDate\` datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`reservation\` ADD \`usersNumber\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`reservation\` ADD \`lengthOfStay\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`reservation\` ADD \`campingType\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`reservation\` ADD \`memberId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`reservation\` ADD \`campgroundId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`review\` ADD \`memberId\` varchar(255) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`review\` ADD \`campgroundId\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`review\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`review\` ADD PRIMARY KEY (\`memberId\`, \`campgroundId\`)`);
        await queryRunner.query(`ALTER TABLE \`tent\` ADD \`tentId\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`tent\` ADD \`campingType\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`tent\` ADD \`residualQuantity\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`tent\` ADD \`weekdayPrices\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`tent\` ADD \`weekendPrices\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`tent\` ADD \`campgroundId\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`theme\` ADD UNIQUE INDEX \`IDX_f2ee91e6c19bde3fb2784d0c88\` (\`campgroundId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_5a9ff2afab984e97e21ae16b41\` ON \`options\` (\`campgroundId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_f2ee91e6c19bde3fb2784d0c88\` ON \`theme\` (\`campgroundId\`)`);
        await queryRunner.query(`ALTER TABLE \`options\` ADD CONSTRAINT \`FK_5a9ff2afab984e97e21ae16b41b\` FOREIGN KEY (\`campgroundId\`) REFERENCES \`campground\`(\`campground_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`dibs\` ADD CONSTRAINT \`FK_fc0b40ae3d13e2dd5469eb8c327\` FOREIGN KEY (\`memberId\`) REFERENCES \`member\`(\`memberId\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`dibs\` ADD CONSTRAINT \`FK_57c4746c5698a73b8f6dadef267\` FOREIGN KEY (\`campgroundId\`) REFERENCES \`campground\`(\`campground_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`referrals\` ADD CONSTRAINT \`FK_97b06170f997f4056fcdc84418d\` FOREIGN KEY (\`memberId\`) REFERENCES \`member\`(\`memberId\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`referrals\` ADD CONSTRAINT \`FK_a50d094e8bbba2532cbde210503\` FOREIGN KEY (\`campgroundId\`) REFERENCES \`campground\`(\`campground_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reservation\` ADD CONSTRAINT \`FK_ac1732818e2540ddcc9045e7fa6\` FOREIGN KEY (\`memberId\`) REFERENCES \`member\`(\`memberId\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reservation\` ADD CONSTRAINT \`FK_71212e957b875d69bd16ebaea4a\` FOREIGN KEY (\`campgroundId\`) REFERENCES \`campground\`(\`campground_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`review\` ADD CONSTRAINT \`FK_7856cc9935938d70ec4d618f828\` FOREIGN KEY (\`memberId\`) REFERENCES \`member\`(\`memberId\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`review\` ADD CONSTRAINT \`FK_fd53a0121383b4aafddfc3f14c4\` FOREIGN KEY (\`campgroundId\`) REFERENCES \`campground\`(\`campground_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tent\` ADD CONSTRAINT \`FK_80020064b242eaf540b471c3b08\` FOREIGN KEY (\`campgroundId\`) REFERENCES \`campground\`(\`campground_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`theme\` ADD CONSTRAINT \`FK_f2ee91e6c19bde3fb2784d0c885\` FOREIGN KEY (\`campgroundId\`) REFERENCES \`campground\`(\`campground_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`theme\` DROP FOREIGN KEY \`FK_f2ee91e6c19bde3fb2784d0c885\``);
        await queryRunner.query(`ALTER TABLE \`tent\` DROP FOREIGN KEY \`FK_80020064b242eaf540b471c3b08\``);
        await queryRunner.query(`ALTER TABLE \`review\` DROP FOREIGN KEY \`FK_fd53a0121383b4aafddfc3f14c4\``);
        await queryRunner.query(`ALTER TABLE \`review\` DROP FOREIGN KEY \`FK_7856cc9935938d70ec4d618f828\``);
        await queryRunner.query(`ALTER TABLE \`reservation\` DROP FOREIGN KEY \`FK_71212e957b875d69bd16ebaea4a\``);
        await queryRunner.query(`ALTER TABLE \`reservation\` DROP FOREIGN KEY \`FK_ac1732818e2540ddcc9045e7fa6\``);
        await queryRunner.query(`ALTER TABLE \`referrals\` DROP FOREIGN KEY \`FK_a50d094e8bbba2532cbde210503\``);
        await queryRunner.query(`ALTER TABLE \`referrals\` DROP FOREIGN KEY \`FK_97b06170f997f4056fcdc84418d\``);
        await queryRunner.query(`ALTER TABLE \`dibs\` DROP FOREIGN KEY \`FK_57c4746c5698a73b8f6dadef267\``);
        await queryRunner.query(`ALTER TABLE \`dibs\` DROP FOREIGN KEY \`FK_fc0b40ae3d13e2dd5469eb8c327\``);
        await queryRunner.query(`ALTER TABLE \`options\` DROP FOREIGN KEY \`FK_5a9ff2afab984e97e21ae16b41b\``);
        await queryRunner.query(`DROP INDEX \`REL_f2ee91e6c19bde3fb2784d0c88\` ON \`theme\``);
        await queryRunner.query(`DROP INDEX \`REL_5a9ff2afab984e97e21ae16b41\` ON \`options\``);
        await queryRunner.query(`ALTER TABLE \`theme\` DROP INDEX \`IDX_f2ee91e6c19bde3fb2784d0c88\``);
        await queryRunner.query(`ALTER TABLE \`tent\` DROP COLUMN \`campgroundId\``);
        await queryRunner.query(`ALTER TABLE \`tent\` DROP COLUMN \`weekendPrices\``);
        await queryRunner.query(`ALTER TABLE \`tent\` DROP COLUMN \`weekdayPrices\``);
        await queryRunner.query(`ALTER TABLE \`tent\` DROP COLUMN \`residualQuantity\``);
        await queryRunner.query(`ALTER TABLE \`tent\` DROP COLUMN \`campingType\``);
        await queryRunner.query(`ALTER TABLE \`tent\` DROP COLUMN \`tentId\``);
        await queryRunner.query(`ALTER TABLE \`review\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`review\` ADD PRIMARY KEY (\`memberId\`)`);
        await queryRunner.query(`ALTER TABLE \`review\` DROP COLUMN \`campgroundId\``);
        await queryRunner.query(`ALTER TABLE \`review\` DROP COLUMN \`memberId\``);
        await queryRunner.query(`ALTER TABLE \`reservation\` DROP COLUMN \`campgroundId\``);
        await queryRunner.query(`ALTER TABLE \`reservation\` DROP COLUMN \`memberId\``);
        await queryRunner.query(`ALTER TABLE \`reservation\` DROP COLUMN \`campingType\``);
        await queryRunner.query(`ALTER TABLE \`reservation\` DROP COLUMN \`lengthOfStay\``);
        await queryRunner.query(`ALTER TABLE \`reservation\` DROP COLUMN \`usersNumber\``);
        await queryRunner.query(`ALTER TABLE \`reservation\` DROP COLUMN \`endDate\``);
        await queryRunner.query(`ALTER TABLE \`reservation\` DROP COLUMN \`startDate\``);
        await queryRunner.query(`ALTER TABLE \`reservation\` DROP COLUMN \`reservationId\``);
        await queryRunner.query(`ALTER TABLE \`referrals\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`referrals\` ADD PRIMARY KEY (\`memberId\`)`);
        await queryRunner.query(`ALTER TABLE \`referrals\` DROP COLUMN \`campgroundId\``);
        await queryRunner.query(`ALTER TABLE \`referrals\` DROP COLUMN \`memberId\``);
        await queryRunner.query(`ALTER TABLE \`dibs\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`dibs\` ADD PRIMARY KEY (\`memberId\`)`);
        await queryRunner.query(`ALTER TABLE \`dibs\` DROP COLUMN \`campgroundId\``);
        await queryRunner.query(`ALTER TABLE \`dibs\` DROP COLUMN \`memberId\``);
        await queryRunner.query(`ALTER TABLE \`options\` DROP INDEX \`IDX_5a9ff2afab984e97e21ae16b41\``);
        await queryRunner.query(`ALTER TABLE \`options\` DROP COLUMN \`campgroundId\``);
        await queryRunner.query(`ALTER TABLE \`options\` DROP COLUMN \`sportsField\``);
        await queryRunner.query(`ALTER TABLE \`options\` DROP COLUMN \`convenienceStore\``);
        await queryRunner.query(`ALTER TABLE \`options\` DROP COLUMN \`athleticFacilities\``);
        await queryRunner.query(`ALTER TABLE \`options\` DROP COLUMN \`walkingTrails\``);
        await queryRunner.query(`ALTER TABLE \`member\` DROP COLUMN \`phoneNumber\``);
        await queryRunner.query(`ALTER TABLE \`member\` DROP COLUMN \`memberId\``);
        await queryRunner.query(`ALTER TABLE \`campground_tag\` DROP COLUMN \`tagName\``);
        await queryRunner.query(`ALTER TABLE \`campground_tag\` DROP COLUMN \`campgroundTagId\``);
        await queryRunner.query(`ALTER TABLE \`tent\` ADD \`campground_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`tent\` ADD \`weekend_prices\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`tent\` ADD \`weekday_prices\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`tent\` ADD \`residual_quantity\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`tent\` ADD \`camping_type\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`tent\` ADD \`tent_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`tent\` ADD PRIMARY KEY (\`tent_id\`)`);
        await queryRunner.query(`ALTER TABLE \`review\` ADD \`campground_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`review\` ADD PRIMARY KEY (\`campground_id\`)`);
        await queryRunner.query(`ALTER TABLE \`review\` ADD \`member_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`review\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`review\` ADD PRIMARY KEY (\`member_id\`, \`campground_id\`)`);
        await queryRunner.query(`ALTER TABLE \`reservation\` ADD \`campground_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`reservation\` ADD \`member_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`reservation\` ADD \`camping_type\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`reservation\` ADD \`length_of_stay\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`reservation\` ADD \`users_number\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`reservation\` ADD \`end_date\` datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`reservation\` ADD \`start_date\` datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`reservation\` ADD \`reservation_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`reservation\` ADD PRIMARY KEY (\`reservation_id\`)`);
        await queryRunner.query(`ALTER TABLE \`referrals\` ADD \`campground_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`referrals\` ADD PRIMARY KEY (\`campground_id\`)`);
        await queryRunner.query(`ALTER TABLE \`referrals\` ADD \`member_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`referrals\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`referrals\` ADD PRIMARY KEY (\`member_id\`, \`campground_id\`)`);
        await queryRunner.query(`ALTER TABLE \`dibs\` ADD \`campground_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`dibs\` ADD PRIMARY KEY (\`campground_id\`)`);
        await queryRunner.query(`ALTER TABLE \`dibs\` ADD \`member_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`dibs\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`dibs\` ADD PRIMARY KEY (\`member_id\`, \`campground_id\`)`);
        await queryRunner.query(`ALTER TABLE \`options\` ADD \`campground_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`options\` ADD PRIMARY KEY (\`campground_id\`)`);
        await queryRunner.query(`ALTER TABLE \`options\` ADD \`sports_field\` tinyint NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`options\` ADD \`convenience_store\` tinyint NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`options\` ADD \`athletic_facilities\` tinyint NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`options\` ADD \`walking_trails\` tinyint NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`member\` ADD \`phone_number\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`member\` ADD \`member_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`member\` ADD PRIMARY KEY (\`member_id\`)`);
        await queryRunner.query(`ALTER TABLE \`campground_tag\` ADD \`tag_name\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`campground_tag\` ADD \`campground_tag_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`campground_tag\` ADD PRIMARY KEY (\`campground_tag_id\`)`);
    }

}
