import {MigrationInterface, QueryRunner} from "typeorm";

export class updateDB1684282676448 implements MigrationInterface {
    name = 'updateDB1684282676448'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`referrals\` DROP FOREIGN KEY \`FK_182bcfe9609544c6a477c8d271a\``);
        await queryRunner.query(`ALTER TABLE \`referrals\` DROP FOREIGN KEY \`FK_5f3c3c8a5675ba108d4a97afd4c\``);
        await queryRunner.query(`ALTER TABLE \`review\` DROP FOREIGN KEY \`FK_4fc3d826482567c71c5abadf713\``);
        await queryRunner.query(`ALTER TABLE \`review\` DROP FOREIGN KEY \`FK_6894343e5e0aa953657f9155785\``);
        await queryRunner.query(`ALTER TABLE \`reservation\` DROP FOREIGN KEY \`FK_3ee158a6028d4a85d47a24e08ea\``);
        await queryRunner.query(`ALTER TABLE \`reservation\` DROP FOREIGN KEY \`FK_8844d667fc05d62eb22f9221942\``);
        await queryRunner.query(`ALTER TABLE \`theme\` DROP FOREIGN KEY \`FK_c4cc250140105903e1fab2587f6\``);
        await queryRunner.query(`ALTER TABLE \`tent\` DROP FOREIGN KEY \`FK_7766209273a5724cd3530f98921\``);
        await queryRunner.query(`DROP INDEX \`REL_c4cc250140105903e1fab2587f\` ON \`theme\``);
        await queryRunner.query(`ALTER TABLE \`theme\` CHANGE \`campgroundCampgroundId\` \`campground_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`referrals\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`referrals\` ADD PRIMARY KEY (\`campgroundCampgroundId\`)`);
        await queryRunner.query(`ALTER TABLE \`referrals\` DROP COLUMN \`memberMemberId\``);
        await queryRunner.query(`ALTER TABLE \`referrals\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`referrals\` DROP COLUMN \`campgroundCampgroundId\``);
        await queryRunner.query(`ALTER TABLE \`review\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`review\` ADD PRIMARY KEY (\`campgroundCampgroundId\`)`);
        await queryRunner.query(`ALTER TABLE \`review\` DROP COLUMN \`memberMemberId\``);
        await queryRunner.query(`ALTER TABLE \`review\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`review\` DROP COLUMN \`campgroundCampgroundId\``);
        await queryRunner.query(`ALTER TABLE \`reservation\` DROP COLUMN \`memberIdMemberId\``);
        await queryRunner.query(`ALTER TABLE \`reservation\` DROP COLUMN \`campgroundIdCampgroundId\``);
        await queryRunner.query(`ALTER TABLE \`tent\` DROP COLUMN \`campgroundIdCampgroundId\``);
        await queryRunner.query(`ALTER TABLE \`referrals\` ADD \`member_id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`referrals\` ADD \`campground_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`referrals\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`referrals\` ADD PRIMARY KEY (\`member_id\`, \`campground_id\`)`);
        await queryRunner.query(`ALTER TABLE \`review\` ADD \`member_id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`review\` ADD \`campground_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`review\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`review\` ADD PRIMARY KEY (\`member_id\`, \`campground_id\`)`);
        await queryRunner.query(`ALTER TABLE \`reservation\` ADD \`member_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`reservation\` ADD \`campground_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`campground\` DROP FOREIGN KEY \`FK_9668e2c5569a5160cf12fe6f53c\``);
        await queryRunner.query(`ALTER TABLE \`dibs\` DROP FOREIGN KEY \`FK_e2f6e4af15c7a834cc8f49ce06f\``);
        await queryRunner.query(`ALTER TABLE \`member\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`member\` DROP COLUMN \`member_id\``);
        await queryRunner.query(`ALTER TABLE \`member\` ADD \`member_id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`dibs\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`dibs\` ADD PRIMARY KEY (\`campground_id\`)`);
        await queryRunner.query(`ALTER TABLE \`dibs\` DROP COLUMN \`member_id\``);
        await queryRunner.query(`ALTER TABLE \`dibs\` ADD \`member_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`dibs\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`dibs\` ADD PRIMARY KEY (\`campground_id\`, \`member_id\`)`);
        await queryRunner.query(`ALTER TABLE \`options\` DROP FOREIGN KEY \`FK_1ff7a175364e99b641a848a5979\``);
        await queryRunner.query(`ALTER TABLE \`options\` DROP PRIMARY KEY`);
        await queryRunner.query(`DROP INDEX \`REL_1ff7a175364e99b641a848a597\` ON \`options\``);
        await queryRunner.query(`ALTER TABLE \`options\` DROP COLUMN \`campground_id\``);
        await queryRunner.query(`ALTER TABLE \`options\` ADD \`campground_id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`options\` ADD UNIQUE INDEX \`IDX_1ff7a175364e99b641a848a597\` (\`campground_id\`)`);
        await queryRunner.query(`ALTER TABLE \`theme\` ADD UNIQUE INDEX \`IDX_337395c357487a28c459b72682\` (\`campground_id\`)`);
        await queryRunner.query(`ALTER TABLE \`tent\` DROP COLUMN \`campground_id\``);
        await queryRunner.query(`ALTER TABLE \`tent\` ADD \`campground_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_1ff7a175364e99b641a848a597\` ON \`options\` (\`campground_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_337395c357487a28c459b72682\` ON \`theme\` (\`campground_id\`)`);
        await queryRunner.query(`ALTER TABLE \`campground\` ADD CONSTRAINT \`FK_9668e2c5569a5160cf12fe6f53c\` FOREIGN KEY (\`member_id\`) REFERENCES \`member\`(\`member_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`dibs\` ADD CONSTRAINT \`FK_e2f6e4af15c7a834cc8f49ce06f\` FOREIGN KEY (\`member_id\`) REFERENCES \`member\`(\`member_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`referrals\` ADD CONSTRAINT \`FK_40b5cf653e8aa21d351d8fd336c\` FOREIGN KEY (\`member_id\`) REFERENCES \`member\`(\`member_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`referrals\` ADD CONSTRAINT \`FK_da6cc01631e0fcfce726d4b6c28\` FOREIGN KEY (\`campground_id\`) REFERENCES \`campground\`(\`campground_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`options\` ADD CONSTRAINT \`FK_1ff7a175364e99b641a848a5979\` FOREIGN KEY (\`campground_id\`) REFERENCES \`campground\`(\`campground_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`review\` ADD CONSTRAINT \`FK_ac708cb4df027ea963e9e4c2977\` FOREIGN KEY (\`member_id\`) REFERENCES \`member\`(\`member_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`review\` ADD CONSTRAINT \`FK_3057c43f6c8146677b959cc75a4\` FOREIGN KEY (\`campground_id\`) REFERENCES \`campground\`(\`campground_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reservation\` ADD CONSTRAINT \`FK_0f5d6689f3c4880b4ced581e87b\` FOREIGN KEY (\`member_id\`) REFERENCES \`member\`(\`member_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reservation\` ADD CONSTRAINT \`FK_73c2d97e266e42ee036f155be6a\` FOREIGN KEY (\`campground_id\`) REFERENCES \`campground\`(\`campground_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`theme\` ADD CONSTRAINT \`FK_337395c357487a28c459b726825\` FOREIGN KEY (\`campground_id\`) REFERENCES \`campground\`(\`campground_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tent\` ADD CONSTRAINT \`FK_5da39bf68581b682a5f931be39e\` FOREIGN KEY (\`campground_id\`) REFERENCES \`campground\`(\`campground_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`tent\` DROP FOREIGN KEY \`FK_5da39bf68581b682a5f931be39e\``);
        await queryRunner.query(`ALTER TABLE \`theme\` DROP FOREIGN KEY \`FK_337395c357487a28c459b726825\``);
        await queryRunner.query(`ALTER TABLE \`reservation\` DROP FOREIGN KEY \`FK_73c2d97e266e42ee036f155be6a\``);
        await queryRunner.query(`ALTER TABLE \`reservation\` DROP FOREIGN KEY \`FK_0f5d6689f3c4880b4ced581e87b\``);
        await queryRunner.query(`ALTER TABLE \`review\` DROP FOREIGN KEY \`FK_3057c43f6c8146677b959cc75a4\``);
        await queryRunner.query(`ALTER TABLE \`review\` DROP FOREIGN KEY \`FK_ac708cb4df027ea963e9e4c2977\``);
        await queryRunner.query(`ALTER TABLE \`options\` DROP FOREIGN KEY \`FK_1ff7a175364e99b641a848a5979\``);
        await queryRunner.query(`ALTER TABLE \`referrals\` DROP FOREIGN KEY \`FK_da6cc01631e0fcfce726d4b6c28\``);
        await queryRunner.query(`ALTER TABLE \`referrals\` DROP FOREIGN KEY \`FK_40b5cf653e8aa21d351d8fd336c\``);
        await queryRunner.query(`ALTER TABLE \`dibs\` DROP FOREIGN KEY \`FK_e2f6e4af15c7a834cc8f49ce06f\``);
        await queryRunner.query(`ALTER TABLE \`campground\` DROP FOREIGN KEY \`FK_9668e2c5569a5160cf12fe6f53c\``);
        await queryRunner.query(`DROP INDEX \`REL_337395c357487a28c459b72682\` ON \`theme\``);
        await queryRunner.query(`DROP INDEX \`REL_1ff7a175364e99b641a848a597\` ON \`options\``);
        await queryRunner.query(`ALTER TABLE \`tent\` DROP COLUMN \`campground_id\``);
        await queryRunner.query(`ALTER TABLE \`tent\` ADD \`campground_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`theme\` DROP INDEX \`IDX_337395c357487a28c459b72682\``);
        await queryRunner.query(`ALTER TABLE \`options\` DROP INDEX \`IDX_1ff7a175364e99b641a848a597\``);
        await queryRunner.query(`ALTER TABLE \`options\` DROP COLUMN \`campground_id\``);
        await queryRunner.query(`ALTER TABLE \`options\` ADD \`campground_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_1ff7a175364e99b641a848a597\` ON \`options\` (\`campground_id\`)`);
        await queryRunner.query(`ALTER TABLE \`options\` ADD PRIMARY KEY (\`campground_id\`)`);
        await queryRunner.query(`ALTER TABLE \`options\` ADD CONSTRAINT \`FK_1ff7a175364e99b641a848a5979\` FOREIGN KEY (\`campground_id\`) REFERENCES \`campground\`(\`campground_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`dibs\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`dibs\` ADD PRIMARY KEY (\`campground_id\`)`);
        await queryRunner.query(`ALTER TABLE \`dibs\` DROP COLUMN \`member_id\``);
        await queryRunner.query(`ALTER TABLE \`dibs\` ADD \`member_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`dibs\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`dibs\` ADD PRIMARY KEY (\`member_id\`, \`campground_id\`)`);
        await queryRunner.query(`ALTER TABLE \`member\` DROP COLUMN \`member_id\``);
        await queryRunner.query(`ALTER TABLE \`member\` ADD \`member_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`member\` ADD PRIMARY KEY (\`member_id\`)`);
        await queryRunner.query(`ALTER TABLE \`dibs\` ADD CONSTRAINT \`FK_e2f6e4af15c7a834cc8f49ce06f\` FOREIGN KEY (\`member_id\`) REFERENCES \`member\`(\`member_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`campground\` ADD CONSTRAINT \`FK_9668e2c5569a5160cf12fe6f53c\` FOREIGN KEY (\`member_id\`) REFERENCES \`member\`(\`member_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reservation\` DROP COLUMN \`campground_id\``);
        await queryRunner.query(`ALTER TABLE \`reservation\` DROP COLUMN \`member_id\``);
        await queryRunner.query(`ALTER TABLE \`review\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`review\` ADD PRIMARY KEY (\`member_id\`)`);
        await queryRunner.query(`ALTER TABLE \`review\` DROP COLUMN \`campground_id\``);
        await queryRunner.query(`ALTER TABLE \`review\` DROP COLUMN \`member_id\``);
        await queryRunner.query(`ALTER TABLE \`referrals\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`referrals\` ADD PRIMARY KEY (\`member_id\`)`);
        await queryRunner.query(`ALTER TABLE \`referrals\` DROP COLUMN \`campground_id\``);
        await queryRunner.query(`ALTER TABLE \`referrals\` DROP COLUMN \`member_id\``);
        await queryRunner.query(`ALTER TABLE \`tent\` ADD \`campgroundIdCampgroundId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`reservation\` ADD \`campgroundIdCampgroundId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`reservation\` ADD \`memberIdMemberId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`review\` ADD \`campgroundCampgroundId\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`review\` ADD PRIMARY KEY (\`campgroundCampgroundId\`)`);
        await queryRunner.query(`ALTER TABLE \`review\` ADD \`memberMemberId\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`review\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`review\` ADD PRIMARY KEY (\`memberMemberId\`, \`campgroundCampgroundId\`)`);
        await queryRunner.query(`ALTER TABLE \`referrals\` ADD \`campgroundCampgroundId\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`referrals\` ADD PRIMARY KEY (\`campgroundCampgroundId\`)`);
        await queryRunner.query(`ALTER TABLE \`referrals\` ADD \`memberMemberId\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`referrals\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`referrals\` ADD PRIMARY KEY (\`memberMemberId\`, \`campgroundCampgroundId\`)`);
        await queryRunner.query(`ALTER TABLE \`theme\` CHANGE \`campground_id\` \`campgroundCampgroundId\` varchar(36) NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_c4cc250140105903e1fab2587f\` ON \`theme\` (\`campgroundCampgroundId\`)`);
        await queryRunner.query(`ALTER TABLE \`tent\` ADD CONSTRAINT \`FK_7766209273a5724cd3530f98921\` FOREIGN KEY (\`campgroundIdCampgroundId\`) REFERENCES \`campground\`(\`campground_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`theme\` ADD CONSTRAINT \`FK_c4cc250140105903e1fab2587f6\` FOREIGN KEY (\`campgroundCampgroundId\`) REFERENCES \`campground\`(\`campground_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reservation\` ADD CONSTRAINT \`FK_8844d667fc05d62eb22f9221942\` FOREIGN KEY (\`memberIdMemberId\`) REFERENCES \`member\`(\`member_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reservation\` ADD CONSTRAINT \`FK_3ee158a6028d4a85d47a24e08ea\` FOREIGN KEY (\`campgroundIdCampgroundId\`) REFERENCES \`campground\`(\`campground_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`review\` ADD CONSTRAINT \`FK_6894343e5e0aa953657f9155785\` FOREIGN KEY (\`campgroundCampgroundId\`) REFERENCES \`campground\`(\`campground_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`review\` ADD CONSTRAINT \`FK_4fc3d826482567c71c5abadf713\` FOREIGN KEY (\`memberMemberId\`) REFERENCES \`member\`(\`member_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`referrals\` ADD CONSTRAINT \`FK_5f3c3c8a5675ba108d4a97afd4c\` FOREIGN KEY (\`memberMemberId\`) REFERENCES \`member\`(\`member_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`referrals\` ADD CONSTRAINT \`FK_182bcfe9609544c6a477c8d271a\` FOREIGN KEY (\`campgroundCampgroundId\`) REFERENCES \`campground\`(\`campground_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
